/getitem GM command item count fix
aosyatnik/Imgeneus pull request #2
Opened 2020-11-28 19:47 UTC by matigramirez

DBItem's Count wasn't being checked before attempting to give items to a player, which resulted in unexpected behavior. I added a check on the Item item itself, to prevent the Count field to surpass the MaxCount field and also a simple fix on the CharacterPacketHandler file to get the expected behaviour.

![ezgif-4-002ba872c7e1](https://user-images.githubusercontent.com/32178801/100524725-355d5b00-3199-11eb-86c0-aee73477cf33.gif)

2020-11-28 23:33 UTC, matigramirez commented
I just reviewed the failing tests (which I hadn't before, sorry about that), apparently when you mock DbItems, the `Count` property is missing on them, which ends up making the InMemory Item object to have Count = 0, which makes the tests fail. 
Editing this line:
![image](https://user-images.githubusercontent.com/32178801/100528193-bbd56500-31b8-11eb-9157-88da1a5409ac.png)
to prevent Count from being 0 should solve the problem.
Editing the tests to include the Count property (this would be closer to the real DbItems) would also solve it.

2020-11-29 19:35 UTC, aosyatnik commented
@matigramirez , thank you for your PR. It looks good, thank you for your contribution! I left some ideas for improvements. Thanks again for your time :)

2020-11-29 19:53 UTC, aosyatnik requested changes

2020-11-29 19:53 UTC, aosyatnik commented on src/Imgeneus.World/Game/Player/CharacterPacketHandlers.cs
> +            byte itemCount = gMGetItemPacket.Count;
Let's stick with the overall code-base and use `var`. I.e.  `var itemCount = gMGetItemPacket.Count;`

2020-11-29 19:53 UTC, aosyatnik commented on src/Imgeneus.World/Game/Player/Item.cs
> +
Please, try not to add empty strings :)

2020-11-29 19:53 UTC, aosyatnik commented on src/Imgeneus.World/Game/Player/CharacterPacketHandlers.cs
> +            while (itemCount > 0)
Overall I like this idea, but... I'm thinking about how comfortable it would be for GM to get some consumables or gems? Maybe it would be better to add another logic for joinable and no joinable items. Let's assume GM uses `/getitem gem_type gem_id 255`, it should create 255 gems in 1 item. If GM calls `/getitem sword_type sword_id 10` he gets 10 swords, that are 10 dirrefent items. What do you think?

Something like this pseudo code:
if (item.IsJoinable){
 var newItem = new Item(_databasePreloader, gMGetItemPacket.Type, gMGetItemPacket.TypeId, itemCount);
...
}
else {
your code
}

2020-11-29 20:15 UTC, matigramirez commented on src/Imgeneus.World/Game/Player/CharacterPacketHandlers.cs
> +            byte itemCount = gMGetItemPacket.Count;
Sure, will do

2020-11-29 20:15 UTC, matigramirez commented on src/Imgeneus.World/Game/Player/Item.cs
> +
Sorry about that, definitely not intentinal

2020-11-29 20:17 UTC, matigramirez commented on src/Imgeneus.World/Game/Player/CharacterPacketHandlers.cs
> +            while (itemCount > 0)
I agree that separating between joinable and non joinable items would be good but this works as expected, when executing the command for stackable items, they get joined. 
Gif for reference:
![getitem-stack](https://user-images.githubusercontent.com/32178801/100552558-bf272a00-3266-11eb-8984-a2ff926ccbc8.gif)

2020-11-30 08:07 UTC, aosyatnik approved these changes

2020-11-30 08:07 UTC, aosyatnik commented
Looks good to me, thank you!

2020-11-30 08:07 UTC, merged