Set player attributes
aosyatnik/Imgeneus pull request #4
Opened 2020-12-03 14:54 UTC by matigramirez

Added set attributes and push to client, including `/set attr value` gm commands.

On the `GMSetAttributePacket` you'll see the enum `CharacterAttributeEnum` which is used throughout most of the methods added. I didn't know where to place this enum because I feel it should be within Player classes but since these are in the World project and the enum is used in the Network project aswell, I can't place it on World. Any ideas where it can be placed better?

This includes a very basic levelling logic needed to validate the level setter (mainly for the gm command), but isn't meant to be the full levelling logic.

Added unit tests for set attributes aswell.

2020-12-03 15:31 UTC, aosyatnik requested changes
You've done great work! I'm sure, it was not easy ;)
My main concern is calling `SendAttribute` from methods when it's not expected. Overall I don't want to mix "business" logic (like setting stats, gold etc.) and "packet" logic.

2020-12-03 15:31 UTC, aosyatnik commented on src/Imgeneus.World/Game/Player/Character.cs
> +            ChangeGold(newGold);
I believe there will be confusion between `ChangeGold` and `SetGold`, because they are doing the same thing. I suggest, that you will remove this method and instead change the way `HandleGMSetAttributePacket` works. I.e.
```
case CharacterAttributeEnum.Money:
                    targetPlayer.ChangeGold(attributeValue);
                    SendAttribute(CharacterAttributeEnum.Money);
                    _packetsHelper.SendGmCommandSuccess(Client);
                    break;
```

2020-12-03 15:31 UTC, aosyatnik commented on src/Imgeneus.World/Game/Player/CharacterLeveling.cs
> +            SendAttribute(CharacterAttributeEnum.Level);
The same goes here. I assume, that we will set level not only via gm command but also when the player kills mobs, makes quests etc. In this case we shouldn't call `SendAttribute(CharacterAttributeEnum.Level)` every time we level up. Let's move `SendAttribute` out of `SetLevel` call.

2020-12-03 15:31 UTC, aosyatnik commented on src/Imgeneus.World/Game/Player/CharacterPacketHandlers.cs
> +            var targetPlayer = _gameWorld.Players.Values.FirstOrDefault(p => p.Name == player);
It's not the first time when I see it (it's not your mistake, but mine). Getting a player like this is time-consuming because we have to potentially go through many records before we find the player, that we need.  We should implement players dictionary, that stores players by name as a key. You can add TODO: comment and create a task in trello for this.

2020-12-03 15:31 UTC, aosyatnik commented on src/Imgeneus.World/Game/Player/CharacterStats.cs
> +            SendAttribute(CharacterAttributeEnum.Kills);
The same goes here: we are likely gonna use this, when implementing pvp between fractions. So `SetKills` will be called not only vis GM call.

I suggest moving `SendAttribute` out of this method. I also suggest checking if `Kills` can get a private set. I.e.:
`public ushort Kills { get; set; }` => `public ushort Kills { get; private set; }`
So that, there won't be confusion for other developers how to call this code `player.Kills = 999` or `player.SetKills(999)`

2020-12-03 15:31 UTC, aosyatnik commented on src/Imgeneus.World/Game/Player/CharacterStats.cs
> +            SendAttribute(CharacterAttributeEnum.Deaths);
Same as for Kills.

2020-12-03 15:31 UTC, aosyatnik commented on src/Imgeneus.World/Game/Player/CharacterStats.cs
> +            SendAttribute(CharacterAttributeEnum.StatPoint);
Same as for Kills. I gues you've already got it :D

2020-12-03 15:31 UTC, aosyatnik commented on src/Imgeneus.Network/Packets/Game/GMSetAttributePacket.cs
> +        public void Deconstruct(out CharacterAttributeEnum attribute, out uint value, out string charname)
Like it :)

2020-12-03 15:31 UTC, aosyatnik commented on src/Imgeneus.Network/Packets/Game/GMSetAttributePacket.cs
> +    public enum CharacterAttributeEnum : byte
I'm fine having it in src/Imgeneus.Network/Packets/Game/ folder. Let's just move it to its' own file. I.e. `CharacterAttributeEnum.cs`

2020-12-03 15:43 UTC, matigramirez commented on src/Imgeneus.World/Game/Player/Character.cs
> +            ChangeGold(newGold);
Yeah I didn't know how to handle this kind of situations either, I will remove the SetGold method altogether

2020-12-03 15:52 UTC, matigramirez commented
At first I had put the `SendAttribute` method call on the GMCommand calls but the thing is they should respect the normal logic for the corresponding attribute. For instance, if I use `/set Mati level 30` this should send the attribute but also send some other things like update main stat points, send level up animation, send required experience for next level, etc.
I agree that this logic shouldn't be part of the Character set methods.
I'll move the `SendAttribute` call to the GMCommand handler but I'll add a TODO to replace them with the complete levelup logic once that is implemented.

2020-12-03 18:27 UTC, matigramirez commented
Moved SendAttribute calls outside of Character Attribute setters as requested.

When casting `attributeValue` to `Mode enum`, if `attributeValue` was superior to `3 (max mode value)` it would be wrongly set. This behavior has been fixed.

For some a reason a Mob test failed on Linux but not on Windows? This shouldn't be an issue caused by this PR.

2020-12-05 11:13 UTC, aosyatnik commented
"For some a reason a Mob test failed on Linux but not on Windows? This shouldn't be an issue caused by this PR." - you are right, I think I've seen this issue several times. I assume it's connected with Timers in a test, timer might randomly fail sometimes. Maybe I need to rewrite this test. So, yes, it's a problem not of this PR.

2020-12-05 11:21 UTC, aosyatnik reviewed
Overall this is very good PR. I left some minor comments like add documentation or use private setters, where it's possible :) Great work!

2020-12-05 11:21 UTC, aosyatnik commented on src/Imgeneus.World/Game/Player/Character.cs
> +using Imgeneus.Network.Packets.Game;
Please, remove the unused namespace.

2020-12-05 11:21 UTC, aosyatnik commented on src/Imgeneus.World/Game/Player/CharacterStats.cs
> +        /// <returns></returns>
It would be nice to write documentation what is param and what it returns.

2020-12-05 11:21 UTC, aosyatnik commented on src/Imgeneus.World/Game/Player/CharacterStats.cs
> +        public uint GetAttributeValue(CharacterAttributeEnum attribute)
Let's write documentation for all public methods.

2020-12-05 11:21 UTC, aosyatnik commented on src/Imgeneus.World/Game/Player/CharacterStats.cs
> +        public void SetStat(CharacterAttributeEnum statAttribute, ushort newStatValue)
Let's write documentation for all public methods.

2020-12-05 11:21 UTC, aosyatnik commented on src/Imgeneus.World/Game/Player/CharacterStats.cs
>          public ushort Luck { get; set; }
Let's check if all stats can have `private set`. The same as you've done for Kills & Deaths

2020-12-05 16:46 UTC, aosyatnik approved these changes

2020-12-05 16:46 UTC, aosyatnik commented
Looks good to me, great work! Merging this in.

2020-12-05 16:47 UTC, merged