implement name change stone
aosyatnik/Imgeneus pull request #7
Opened 2020-12-04 00:17 UTC by matigramirez

This PR implements all the name change process.
Client asks for name change -> Character database field `IsRename` is set to true -> When user goes to character screen he will be prompted to set a new name -> server will validate if name is on use -> send success/error packet to client -> set new name and save it to database.
The response statuses for the name change that I found are  1 = success, 2 = name already in use... I don't know what 0 means (if it means something) but I'll try to find out if there are some other status codes. For the moment, this works fine for the mentioned cases.

2020-12-04 00:40 UTC, matigramirez commented
Just checked and there's no server side validation on character names. I bypassed client validation easily on OS.
![image](https://user-images.githubusercontent.com/32178801/101106198-53b6c280-35ae-11eb-8554-9e6143b7fdf1.png)

I think we should add some validation rules for charnames, what do you think?

2020-12-05 11:29 UTC, aosyatnik requested changes
Looks good, but maybe requires some improvements, especially remove the item from inventory.

2020-12-05 11:29 UTC, aosyatnik commented on src/Imgeneus.World/SelectionScreen/SelectionScreenManager.cs
> +            var characterWithNewName = await database.Characters.FirstOrDefaultAsync(c => c.UserId == _client.UserID && c.Name == newName);
Looks like here you need to check if there is any character among **all** users, that has the same name. So I think the check should look like this: `await database.Characters.FirstOrDefaultAsync(c => c.Name == newName);`

2020-12-05 11:29 UTC, aosyatnik commented on src/Imgeneus.World/SelectionScreen/SelectionScreenManager.cs
> +            // TODO: Should charname be validated somehow? for eg in case someone skips client validation for symbols or something else?
Yes, let's add simple validation, that name shouldn't contain symbols like spaces, *, ", ' etc. Only letters, numbers and underscore.

2020-12-05 11:29 UTC, aosyatnik commented on src/Imgeneus.World/Game/Player/CharacterInventory.cs
> +        public void UseNameChangeStone()
I don't see any update of the inventory item. If the player uses a name store, a name store should be removed from inventory, right? Let's also write tests for this.

2020-12-05 13:43 UTC, matigramirez commented on src/Imgeneus.World/Game/Player/CharacterInventory.cs
> +        public void UseNameChangeStone()
Name change stones are consumable items like potions so the item is already removed once it is consumed.
This behavior is done in the `UseItem(byte bag, byte slot)` method on the `CharacterInventory.cs` file. This method includes a call to `ApplyItemEffect(item)` which sees if the item effect is of type `NameChange` and does the rest of the process.

2020-12-05 13:44 UTC, matigramirez commented on src/Imgeneus.World/SelectionScreen/SelectionScreenManager.cs
> +            // TODO: Should charname be validated somehow? for eg in case someone skips client validation for symbols or something else?
Alright, this validation should also be done when first creating a character, should I implement this for both cases in another PR? since it's linked to both methods.

2020-12-05 13:45 UTC, matigramirez commented on src/Imgeneus.World/SelectionScreen/SelectionScreenManager.cs
> +            var characterWithNewName = await database.Characters.FirstOrDefaultAsync(c => c.UserId == _client.UserID && c.Name == newName);
You're right. I meant to do this, I don't know why I included the UserId in there.

2020-12-05 15:45 UTC, aosyatnik commented on src/Imgeneus.World/SelectionScreen/SelectionScreenManager.cs
> +            // TODO: Should charname be validated somehow? for eg in case someone skips client validation for symbols or something else?
Yes, you are right, let's do it as separate feature in another PR.

2020-12-05 15:46 UTC, aosyatnik commented on src/Imgeneus.World/Game/Player/CharacterInventory.cs
> +        public void UseNameChangeStone()
You are absolutely right. Forget what I wrote :D

2020-12-05 15:53 UTC, aosyatnik approved these changes

2020-12-05 15:53 UTC, aosyatnik commented
Cool, great work! Merging this in, thanks :)

2020-12-05 15:53 UTC, merged